name: 'Alpha'
description: 'Alpha'
inputs:
  CONFIGURATION:
    required: false
    default: 'Release'
  DOTNET_CORE_VERSION: 
    required: false
    default: '9.x'
  GITHUB_TOKEN:
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.DOTNET_CORE_VERSION }}

    - name: Build
      run: dotnet build --configuration ${{ inputs.CONFIGURATION }} /p:Version=0.0.0 /p:AssemblyVersion=0.0.0.0
      shell: bash

    - name: Test
      run: dotnet test --configuration ${{ inputs.CONFIGURATION }} --no-build
      shell: bash

    - name: Publish
      run: |
        dotnet publish ${{ github.workspace }}/src/Bastet --configuration ${{ inputs.CONFIGURATION }} --no-build --output ${{ github.workspace }}/publish
      shell: bash

    - name: Docker Build
      run: |
          echo "${{ inputs.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build ${{ github.workspace }}/publish --file ${{ github.workspace }}/src/Bastet/Dockerfile --tag=ghcr.io/${{ github.repository_owner }}/bastet:alpha
          docker push -a ghcr.io/${{ github.repository_owner }}/bastet
      shell: bash
