name: Build
on:
  push:
    branches:
    - release/[0-9]+.[0-9]+
  workflow_dispatch:

concurrency: build

permissions:
  packages: write
  content: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build/
        name: Build
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
